### ISSUE TITLE
Some banking apps will detect Xposed hooks

### ISSUE THREAD

**Issue by danielphan2003** [alexdonh/no-accessibility-services#1]
Some banking apps (e.g. VCB Digibank, BIDV... and several banking apps in Vietnam) detect Xposed hooks when you enable the module. I don't think there is a solution for this, but it would be awesome if this is solvable.

**Comment by IntelCorei5-8350u** [comment]
> Some banking apps (e.g. VCB Digibank, BIDV... and several banking apps in Vietnam) detect Xposed hooks when you enable the module. I don't think there is a solution for this, but it would be awesome if this is solvable.

Looking at this guy's profile I will assume he is also a Vietnamese like all of us (surname is a dead giveaway), and surprisingly he overlooked all of this. I really hoped it will work in the future to reduce steps for rooted users.

Currently you can configure Tasker app to automatically disable accessibility services when you open a banking app, works for both rooted and nonroot users. 
Guide (vozforums): https://voz.vn/t/cac-app-ngan-hang-dang-bat-dau-cap-nhat-chan-cac-ung-dung-khac-truy-cap-ho-tro-tiep-can-accessibility.812505/post-27046403

**Comment by alexdonh** [comment]
> Some banking apps (e.g. VCB Digibank, BIDV... and several banking apps in Vietnam) detect Xposed hooks when you enable the module. I don't think there is a solution for this, but it would be awesome if this is solvable.

Interesting! 

A guy in XDA also mentiond BIDV app. I gave these apps a quick try. VCB Digibank allows me to continue with login screen (still theres nag saying im rooted) I dont have an account to continue unfortunately. BIDV stops me with "debug device" warning... perhaps thats another check. Im using neither of them so Im still fine I guess. Its understandable that apps may behave differently. For example SCB EASY app, I cant get it to open. It passes the SecurityBlockActivity but crashes somewhere at SplashActivity. When I have more time I will definitely give a little more of digging. 

Feel free to come up with ideas. Im all ears!

**Comment by alexdonh** [comment]
> > Some banking apps (e.g. VCB Digibank, BIDV... and several banking apps in Vietnam) detect Xposed hooks when you enable the module. I don't think there is a solution for this, but it would be awesome if this is solvable.
> 
> Looking at this guy's profile I will assume he is also a Vietnamese like all of us (surname is a dead giveaway), and surprisingly he overlooked all of this. I really hoped it will work in the future to reduce steps for rooted users.
> 
> Currently you can configure Tasker app to automatically disable accessibility services when you open a banking app, works for both rooted and nonroot users. Guide (vozforums): https://voz.vn/t/cac-app-ngan-hang-dang-bat-dau-cap-nhat-chan-cac-ung-dung-khac-truy-cap-ho-tro-tiep-can-accessibility.812505/post-27046403

I dont know if nationality has anything to do with all this but thanks anyway. I see quite a few people using Tasker for that and it seems to work. Theres also another way of using Tasker: use variable to temporarily unset/reset the `enabled_accessibility_services` secure flag. Im not entirely sure if it works though. 

I have an idea of making an app that can:

1. switch `enabled_accessibility_services` on/off using Quick Settings tile
2. with `android.permission.READ_LOGS` permission one-time granted by `adb`, the ability to switch on/off automatically when target apps open.. 

Lets see if I can make time for it.. 

Cheers!

**Comment by IntelCorei5-8350u** [comment]
You can make a standalone app with Tasker, but it's closed source and quite
complicated. If the app can be open sourced then much appreciated.

One thing of the tasker way is that the banking app may detect the
accessibility being on before tasker can turn the service off, often on
faster devices. There should be a feature to offset the time between
accessibility service being off and when the banking app opens
